### ISSUE TITLE
Require Cyrcle

### ISSUE THREAD

**Issue by sajaddp** [adivery/adivery-react-native-plugin#1]
سلام
هنگام اجرای پلاگین پیام زیر ظاهر می شود. به نظر می رسد مشکل حلفه بی نهایت ایجاد شده.

```
Require cycle: node_modules/adivery/src/index.tsx -> node_modules/adivery/src/adivery-banner-ad-view.tsx -> node_modules/adivery/src/index.tsx
```

**Comment by shayan4shayan** [comment]
سلام
لطفا ورژن نسخه ای که مشکل رو دریافت کردید رو برای بنده ارسال کنید.

**Comment by sajaddp** [comment]
`4.2.4`

**Comment by shayan4shayan** [comment]
روی آخرین کامیت این ریپازیتوری فیکس شد
به زودی نسخه ۴.۲.۵ ریلیز میشه و مشکل حل میشه.
