### ISSUE TITLE
خطای Undefined

### ISSUE THREAD

**Issue by sajaddp** [adivery/adivery-react-native-plugin#2]
سلام
هنگام اجرای کد با خطای `Undefined` مواجه می شویم.
منظور از این خطا چیست؟
شما در قسمت `Usage` نوشته اید که مقدار `adiveryAppId` یک رشته توکن هست ولی پشتیبانی ادیوری در تماس تلفنی اعلام کرد که نام پکیج هست. کدام مورد را تایید می فرمایید؟

بنده هم داکیومنت موجود در سایت را بررسی کردم و هم موارد موجود در گیت هاب، داکیومنت ها متفاوت هست ولی در هر صورت خطا دریافت می کنم.

**Comment by shayan4shayan** [comment]
سلام مقدار `adiveryAppId` یک رشته `UUID` هست و توی پنل ادیوری از بخش تنظیمات اپلیکیشن میتونید مقدارش رو دریافت کنید.
